version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - 6729:80
      - 443:443
    volumes:
      - ./data:/data
      - ./data/uploads:/app/wp-content/uploads
      - ./src:/app/wp-content/themes/alec-rust
    environment:
      DB_NAME: alecrust
      DB_PASS: root
      THEMES: >-
         [local]alec-rust
      PLUGINS: >-
        attachments,
        contact-form-7,
        sendgrid-email-delivery-simplified,
        zigtweets
      SEARCH_REPLACE: https://www.alecrust.com,http://localhost:6729
      WP_DEBUG: 'true'
  db:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data: {}
