version: '3'
services:
  wordpress:
    image: visiblevc/wordpress:0.15.2-php7.1
    ports:
      - 6729:80
      - 443:443
    volumes:
      - ./data:/data
      - ./data/uploads:/app/wp-content/uploads
      - ./:/app/wp-content/themes/alec-rust
    environment:
      DB_NAME: alecrust
      DB_PASS: root
      THEMES: >-
         [local]alec-rust
      PLUGINS: >-
        attachments,
        contact-form-7,
        sendgrid-email-delivery-simplified,
        zigtweets
      URL_REPLACE: https://www.alecrust.com,http://localhost:6729
      WP_DEBUG: 'true'
  db:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
volumes:
  data:
